service: example-kibo-cloud-service

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  timeout: 30
  environment:
    stage: ${self:provider.stage}
    appKey: ${file(mozu.config.${opt:stage}.json):appKey}
    sharedSecret: ${file(mozu.config.${opt:stage}.json):sharedSecret}
    tenant: ${file(mozu.config.${opt:stage}.json):tenant}
    site: ${file(mozu.config.${opt:stage}.json):site}
    baseUrl: ${file(mozu.config.${opt:stage}.json):baseUrl}
    domain: ${file(mozu.config.${opt:stage}.json):domain}

functions: 
  app:
    handler: src/app.handler
    events: 
      # Every day at 3AM CT
      - schedule: cron(0 8 ? * * *)
    
package:
  individually: false
  include:
    - mozu.config.json
    - mozu.config.*.json
    - node_modules/**